config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#home'

  get "up" => "rails/health#show", as: :rails_health_check

  post "events/:id/event", to: "events#updatelist", as: :updatelist

  resources :events

  get "events/:id/event", to: "events#saveandshowdashboard", as: :addinginfobeforesave

  get "/dashboard", to: "events#showdashboard", as: :dashboard

  patch "events/:id/dashboard", to: "events#update_from_edit_event", as: :update_from_edit_event

  get "events/:id/share", to: "events#share", as: :share

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  attr_reader :new_subject

  OCCASIONS = %w[Noël Anniversaire Saint-Valentin Fêtes\ des\ parents Fête\ des\ grands-mères Pot\ de\ départ
              Crémaillère Baptème Mariage Aïd\ el\ Fitr Bar-Mitzvah Bat-Mitzvah Baby\ shower
              EVJF EVG Remise\ de\ diplôme Juste\ comme\ ça]
  INTERESTS = %w[Musique Sport Nature Art Voyage Lecture Cuisine Technologie Mode Bien-être Cosmétique Humour Cinéma
              Jardinage Jeux-vidéo Langues\ étrangères Astronomie Bricolage Danse Théatre Spectacle Histoire
              Psychologie Développement\ personnel Sptiritualité Astrologie Design]
  LIENS = %w[Parent Petit·e-ami·e Frère Soeur Enfant Collègue Grand-parent Cousin·e Oncle Tante Beau-parent
          Beau-frère Belle-soeur Neveu Nièce Petit-enfant BFF Ami·e Conjoint·e Connaissance Patron·ne
          Parrain Marraine Filleul·e Professeur·e Moi-même]

  def content(client, lien, subject, budget_min, budget_max, genre, occasion, age, _id, _user_id)
    chaptgpt_response = client.chat(
      parameters: {
        model: ENV["MODEL"],
        messages: [
          {
            role: "user",
            content: "Je veux une liste de trente cadeaux pour #{lien}, cette personne est de sexe #{genre}, cette personne est âgée de #{age} ans, cette personne aime #{subject.join(', ')}, le cadeau sera offert à l’occasion de #{occasion}, mon budget se situe entre #{budget_min} euros et #{budget_max} euros. Je veux que le résultat soit intégré dans une liste numérotée."
          }
        ]
      }
    )
    chaptgpt_response["choices"][0]["message"]["content"]
  end

  def update_content(post_prompt, client)
    chaptgpt_response = client.chat(
      parameters: {
        model: ENV["MODEL"],
        messages: [
          {
            role: "user",
            content: "A partir de la liste générée(#{list}), je t'avais demandé une liste de trente cadeaux pour #{lien} qui est âgée de #{age} ans et est de sexe #{genre}.Ce cadeau sera offert à l'occasion de #{occasion}, je t'avais précisé que cette personne aime #{subject.join(', ')}. Je veux que tu prennes en compte ce commentaire: #{post_prompt} et que tu me donnes une nouvelle liste numérotée. Ta réponse ne doit inclure rien d'autre que cette nouvelle liste numérotée."
          }
        ]
      }
    )
    return chaptgpt_response["choices"][0]["message"]["content"]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_client, only: [:create, :update, :showdashboard, :update_from_edit_event, :updatelist]
  # Page d'acceuil
  def home
  end

  # Affichage des critères
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.list = @event.content($client, @event.lien, @event.subject, @event.budget_min, @event.budget_max, @event.genre, @event.occasion, @event.age,@event.user_id ,@event.id).scan(/\s(.*)/).flatten.map { |match| match.gsub(/\d+\.\s/, "") }
    if @event.save
      respond_to do |format|
        format.json { render json: @event, status: :created }
      end
    else
      render 'new'
    end
  end

  # Affiche de la list
  def show
    @event = Event.find(params[:id])
  end

  # Modification de la liste de cadeaux
  def update
    @event = Event.find(params[:id])
    post_prompt = params[:post_prompt]
    @event.update(list: @event.update_content(post_prompt, $client)
                              .scan(/\s(.*)/)
                              .flatten.map { |match| match.gsub(/\d+\.\s/, "") })
    while @event.list.count == 1
      @event.update(list: @event.update_content(post_prompt, $client)
                                .scan(/\s(.*)/)
                                .flatten.map { |match| match.gsub(/\d+\.\s/, "") })
    end
    redirect_to event_path
  end

  # modif de levenement une fois crée
  def update_from_edit_event
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to share_path(@event)
    else
      render :update_from_edit_event, status: :unprocessable_entity
    end
  end

  def updatelist
    @event = Event.find(params[:id])
    @event.update_column(:list, params[:event][:list])
    if @event.save
      # Commentez ou supprimez cette ligne pour désactiver temporairement la redirection
      respond_to do |format|
        format.json { render json: @event }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # ca j'ai pas compris
  def saveandshowdashboard
    @event = Event.find(params[:id])
  end

  # Génération d'un lien pour partager la liste
  def share
    @event = Event.find(params[:id])
  end

  def showdashboard
    @events = Event.where(user: current_user)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    if Event.where(user_id: current_user).count == 0
      redirect_to root_path
    elsif @event.nil?
      redirect_to root_path
    else
      redirect_to dashboard_path
    end
  end

  private

  def set_client
    $client = $client ? $client : OpenAI::Client.new
  end

  def event_params
    params.require(:event).permit([list: []], :event_name, :event_date, :event_url, :cagnotte_url, :occasion, :genre, :budget_min, :budget_max, [subject: []], :age, :lien, :user_id, :client, :response, :custom_interest, :id, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper

  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
  end
end

app/views/events/home.html.erb
<div class= "body-container" >
<h1 class="page-title home">Mes prochains évènements</h1>
<div class= "body-category" ><h4>Noël</h4><h5>dans 3 jours</h5></div>
<div class= "body-category" ><h4>Crémaillère de Candice</h4><h5>dans 2 semaines</h5></div>
<div class= "body-category" ><h4>Anniv de Lolo le charo</h4><h5>le mois prochain</h5></div>
<%= link_to 'Trouver un cadeau', new_event_path, class: "big-btn" %>
<a class="hidden-container" href="https://shattereddisk.github.io/rickroll/rickroll.mp4"> hhhhhhhhhhh</a>
</div>

app/views/events/new.html.erb
<div class="body-container" data-controller="chatgpt-request">
  <div class="loader d-none" data-chatgpt-request-target="loader">
    <div id="loader-wrapper">
			<div id="page">
        <div id="phrase_box">
          <svg width="100%" height="100%">
            <defs>
              <style type="text/css">
              @font-face {
              font-family: "Proxima";
              src: url('');
              }
              </style>
              <mask id="mask" maskUnits="userSpaceOnUse" maskContentUnits="userSpaceOnUse">
                <linearGradient id="linearGradient" gradientUnits="objectBoundingBox" x2="0" y2="1">
                <stop stop-color="white" stop-opacity="0" offset="0%"/>
                <stop stop-color="white" stop-opacity="1" offset="30%"/>
                <stop stop-color="white" stop-opacity="1" offset="70%"/>
                <stop stop-color="white" stop-opacity="0" offset="100%"/>
                </linearGradient>
                <rect width="100%" height="100%" fill="url(#linearGradient)"/>
              </mask>
            </defs>
            <g width="100%" height="100%" style="mask: url(#mask);">
              <g id="phrases"></g>
            </g>
          </svg>
        </div>
        <div id="ighex">
          <div class="preloader loading">
            <span class="slice"></span>
            <span class="slice"></span>
            <span class="slice"></span>
            <span class="slice"></span>
            <span class="slice"></span>
            <span class="slice"></span>
          </div>
        </div>
	  	</div>


	</div>
  </div>

  <%= simple_form_for @event, data: { chatgpt_request_target: "form", action: "submit->chatgpt-request#fetchApi"} do |f| %>
  <h1 class="page-title">Trouve le Geeft parfait</h1>

    <div class="form" data-controller="find-values checkboxes">
      <div class="body-category" data-controller="budget-range">
        <div class="category-title" id="budget-title">Budget</div>
          <div class="price-content">
            <label>Min :</label>
            <label id="min-value" data-budget-range-target="min"></label>
            <label>- Max :</label>
            <label id="max-value"  data-budget-range-target="max"></label>
        </div>
        <div class="range-slider" data-find-values-target="rangeSlider">
          <div class="range-fill" data-budget-range-target="fill"></div>
            <input
              data-budget-range-target="input"
              name="event[budget_min]"
              type="range"
              class="min-price"
              value="100"
              min="10"
              max="1000"
              step="10"
            />
            <input
              data-budget-range-target="input"
              name="event[budget_max]"
              type="range"
              class="max-price"
              value="250"
              min="10"
              max="1000"
              step="10"
            />
        </div>
        <div>
          <%= f.range_field :budget_min, min: 5, max: 500, step: 5, data: { budget_range_target: "starting" }  %>
        </div>
        <div>
          <%=  f.range_field :budget_max, min: 10, max: 1000, step: 10, data: { budget_range_target: "ending" } %>
        </div>
      </div>

      <div class="body-category" id="age-category">
        <%= f.label :age, class: "category-title" %>
        <div class="crit-age">
        <label class = "age-value" data-find-values-target="ageValue">
        </label>
          <div class="range-slider range-age" data-find-values-target="rangeAge">
              <div class="range-fill" data-budget-range-target="fill"></div>
              <input
                name="event[age]"
                min="1"
                max="100"
                type="range"
                step="1"
                class="min-age"
                value="30"
                data-find-values-target="age"
                data-action="input->find-values#ageUpdate"
              />
          </div>
        </div>
        </div>
      </div>

      <div class="body-category">
        <div class="crit-genre" data-controller="gender-check">
          <%# cacher cette partie pour intégrer juste des boutons qui active la valeur à intégrer au form %>
          <%= f.input :genre, collection: ['neutral', 'female', 'male'], as: :radio_buttons, input_html: { data: { target: "gender" } } %>
          <div class="genre-buttons">
            <div class="genre-button neutral" data-action="click->gender-check#neutral"><i class="fa-solid fa-mars-and-venus"></i></div>
            <div class="genre-button female" data-action="click->gender-check#female"><i class="fa-solid fa-venus"></i></div>
            <div class="genre-button male" data-action="click->gender-check#male"><i class="fa-solid fa-mars"></i></div>
          </div>
        </div>
      </div>

      <div class="body-category">
        <div class="crit-lien">
          <%= f.input :lien, collection: Event::LIENS.sort, as: :radio_buttons, input_html: { class: "pill-lien", data: { action: "click->checkboxes#checked" } } %>
        </div>
      </div>

      <div class="body-category">
        <div class="crit-occasion">
          <%= f.input :occasion, collection: Event::OCCASIONS.sort, as: :radio_buttons, input_html: { class: "pill-occasion", data: { action: "click->checkboxes#checked" } } %>
        </div>
      </div>

    <div data-controller="custom-interest">
      <div class="body-category">
        <div class="crit-interest" data-custom-interest-target="divInterest">
          <legend class="col-form-label pt-0">Centre d'intérêts</legend>
          <div class="interest-comment">(3 maximum)</div>
          <%= f.input :subject, label: "", collection: Event::INTERESTS.sort, as: :check_boxes, include_hidden: false, input_html: { class: "pill-interest", data: { action: "click->checkboxes#checked" } }  %>
        </div>
      </div>

      <div class="body-category">
        <div class="crit-custom-interest" >
          <legend class="col-form-label pt-0">Ajoute ton propre intérêt</legend>
          <div class="interest-comment">(1 maximum)</div>
          <div class="custom-input">
            <%= f.input :new_subject, label: "", input_html: { data: { custom_interest_target: "inputInterest" } }, maxlength: 20 %>
          </div>
          <div class="custom-input">
            <input type="text" id="new-input-box" class="new-input">
            <button data-action="click->custom-interest#addcustominterestasapill" class="function-btn" id="addButton" disabled>
              <i class="fa-solid fa-plus"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
    <%= f.submit 'go geeft', class: "big-btn" %>
    <% end %>
  </div>
</div>

<script>

  // Injection du texte dans le formulaire
  // Sélectionnez les éléments input
  var sourceInput = document.getElementById('new-input-box');
  var targetInput = document.getElementById('event_new_subject');
  var addButton = document.getElementById('addButton')

  // Vérifiez si les éléments existent avant de continuer
  if (sourceInput && targetInput) {
      // Ajoutez un écouteur d'événements pour détecter les changements de valeur dans le champ source
      sourceInput.addEventListener('keyup', function() {
        // Copiez la valeur du champ source dans le champ cible
        addButton.removeAttribute('disabled')
        targetInput.value = sourceInput.value.charAt(0).toUpperCase() + sourceInput.value.slice(1);
        if (sourceInput.value === "") {
          addButton.setAttribute('disabled', true)
        }
      });
  }


  var checkmarkIdPrefix = "loadingCheckSVG-";
var checkmarkCircleIdPrefix = "loadingCheckCircleSVG-";
var verticalSpacing = 50;

function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
    return array;
}

function createSVG(tag, properties, opt_children) {
  var newElement = document.createElementNS("http://www.w3.org/2000/svg", tag);
  for(prop in properties) {
    newElement.setAttribute(prop, properties[prop]);
  }
  if (opt_children) {
    opt_children.forEach(function(child) {
      newElement.appendChild(child);
    })
  }
  return newElement;
}

function createPhraseSvg(phrase, yOffset) {
  var text = createSVG("text", {
    fill: "white",
    x: 50,
    y: yOffset,
    "font-size": 18,
    "font-family": "Arial"
  });
  text.appendChild(document.createTextNode(phrase + "..."));
  return text;
}
function createCheckSvg(yOffset, index) {
  var check = createSVG("polygon", {
    points: "21.661,7.643 13.396,19.328 9.429,15.361 7.075,17.714 13.745,24.384 24.345,9.708 ",
    fill: "rgba(255,255,255,1)",
    id: checkmarkIdPrefix + index
  });
  var circle_outline = createSVG("path", {
    d: "M16,0C7.163,0,0,7.163,0,16s7.163,16,16,16s16-7.163,16-16S24.837,0,16,0z M16,30C8.28,30,2,23.72,2,16C2,8.28,8.28,2,16,2 c7.72,0,14,6.28,14,14C30,23.72,23.72,30,16,30z",
    fill: "white"
  })
  var circle = createSVG("circle", {
    id: checkmarkCircleIdPrefix + index,
    fill: "rgba(255,255,255,0)",
    cx: 16,
    cy: 16,
    r: 15
  })
  var group = createSVG("g", {
    transform: "translate(10 " + (yOffset - 20) + ") scale(.9)"
  }, [circle, check, circle_outline]);
  return group;
}

function addPhrasesToDocument(phrases) {
  phrases.forEach(function(phrase, index) {
    var yOffset = 30 + verticalSpacing * index;
    document.getElementById("phrases").appendChild(createPhraseSvg(phrase, yOffset));
    document.getElementById("phrases").appendChild(createCheckSvg(yOffset, index));
  });
}

function easeInOut(t) {
  var period = 200;
  return (Math.sin(t / period + 100) + 1) /2;
}

document.addEventListener("DOMContentLoaded", function(event) {
  addPhrasesToDocument(phrases);
  var start_time = new Date().getTime();
  var upward_moving_group = document.getElementById("phrases");
  upward_moving_group.currentY = 0;
  var checks = phrases.map(function(_, i) {
    return {check: document.getElementById(checkmarkIdPrefix + i), circle: document.getElementById(checkmarkCircleIdPrefix + i)};
  });
  function animateLoading() {
    var now = new Date().getTime();
    upward_moving_group.setAttribute("transform", "translate(0 " + upward_moving_group.currentY + ")");
    upward_moving_group.currentY -= 1.35 * easeInOut(now);
    checks.forEach(function(check, i) {
      var color_change_boundary = - i * verticalSpacing + verticalSpacing + 15;
      if (upward_moving_group.currentY < color_change_boundary) {
        var alpha = Math.max(Math.min(1 - (upward_moving_group.currentY - color_change_boundary + 15)/30, 1), 0);
        check.circle.setAttribute("fill", "rgba(255, 255, 255, " + alpha + ")");
        var check_color = [Math.round(255 * (1-alpha) + 120 * alpha), Math.round(255 * (1-alpha) + 154 * alpha)];
        check.check.setAttribute("fill", "rgba(255, " + check_color[0] + "," + check_color[1] + ", 1)");
      }
    })
    if (now - start_time < 30000 && upward_moving_group.currentY > -710) {
      requestAnimationFrame(animateLoading);
    }
  }
  //animateLoading();
});
</script>

app/views/events/save.html.erb
<h1>Créé ton evenement avec Geeft</h1>


<div>
  <%= simple_form_for @event do |f| %>
    <%= f.input :event_name, input_html: { maxlength: 50 } %>
    <%= f.input :event_date, as: :string,  input_html: {data: { controller: "datepicker" }} %>
    <%= f.input :description, as: :text, input_html: { maxlength: 500 } %>
    <%= f.input :event_url %>
  <% end %>
</div>
<div>
  <%= @event.occasion %>
  <%= @event.lien %>

</div>

app/views/events/saveandshowdashboard.html.erb
<div class="body-container">
  <h1>Crée ton évènement</h1>
    <%= simple_form_for @event, url: :update_from_edit_event do |f| %>
      <div class="top-page">
          <% pronom = case @event.occasion
                      when "Anniversaire", "Pot de départ", "Baptême", "Mariage", "EVJF", "EVG"
                      "son"
                      when "Saint-Valentin", "Fêtes des parents", "Fêtes des grands-mères"
                      "la"
                      when "Crémaillère", "Bar-Mitzvah", "Bat-Mitzvah", "Baby shower", "Remise de diplôme"
                      "sa"
                      when "Aïd el Fitr"
                      "l'"
                      else
                      ""
          end %>
          <div id="card-share-event">
            <p>À l'occasion de <%= pronom %> <%= @event.occasion %> </p>
          </div>


          <div class="card-share-date">
            <%= f.input :event_date, label: "Date de l'évènement :", as: :string, input_html: { data: { controller: "datepicker", class: "date-label" } }%>
          </div>
      </div>



      <div class="card-share-name">
        <%= f.input :event_name, label: "Nom de ton evenement :", placeholder:"Birthday-Bash Yohan...", input_html: { maxlength: 50 , id: "name"} %>
      </div>



      <div class="card-share">
        <%= f.input :description, label: "Notes", as: :text, placeholder:"J'ai trouvé de merveilleuses idées pour...", input_html: { maxlength: 500, id: "description", class: "share-label"} %>
      </div>

      <div class="card-share">
        <%= f.input :cagnotte_url, label: "Cagnotte", placeholder:"www.leetchi/...",input_html: { id: "cagnotte" } %>
      </div>


      <%= f.submit 'Enregistrer ma liste', class: "big-btn" %>
    <% end %>
  </div>


  </div>
</div>

app/views/events/share.html.erb
<div class= "body-container" >
  <div class="share-page-title">
    <h1 class="page-title"><%= @event.event_name %></h1>
    <div class="edit-delete-share-buttons">
      <% if @event.user == current_user %>
        <%= link_to ('<i class="fa-solid fa-pen"></i>').html_safe, addinginfobeforesave_path(@event), class: "btn" %>
        <%= link_to ('<i class="fa-regular fa-trash-can"></i>').html_safe, event_path(@event), class: "btn", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        <input class="input-to-hide" id="post-shortlink" value="https://www.geeft.club/events/<%= @event.id %>/share">
        <%= button_tag ('<i class="fa-solid fa-arrow-up-from-bracket"></i>').html_safe, class: "btn button", id: "copy-button", data: { clipboard_target: "#post-shortlink" } %>
      <% end %>
    </div>
  </div>
  <div class="alert alert-light d-none" id="flash-link" role="alert">
  🔗 Lien copié !
  </div>

  <div class="gift-list" id="geefts">
    <% if @event.event_date.present? %>
      <div class="date-overflow">
          <p><%= @event.event_date.strftime("%d/%m/%Y") %></p>
      </div>
    <% end %>
      <h2 class="category-title share-title">Ma liste de geefts</h2>
      <% @event.list.each do |gift| %>
        <div class="gift-item-row">
          <div class="gift-item">
            <%= gift %>
          </div>
        </div>
      <% end %>
  </div>
  <% if @event.description != "" %>
    <div class="gift-list" id="geefts">
        <h2 class="category-title share-title">Notes</h2>
        <div class= "gift-item-row">
          <div class="gift-item">
            <%= @event.description %>
          </div>
        </div>

    </div>
  <% end %>

    <% if @event.cagnotte_url != "" %>
      <div class="gift-list" id="geefts">
        <h2 class="category-title share-title">Cagnotte</h2>
        <div class= "gift-item-row">
          <div class="gift-item">
            <a href="https://<%= @event.cagnotte_url %>" target="_blank"><%= @event.cagnotte_url %></a>
          </div>
        </div>
      </div>
  <% end %>

 </div>

<script>
  (function(){
    new Clipboard('#copy-button');
  })();

    // Fonction pour afficher la div flash-link
  function showFlashLink() {
    var flashLink = document.getElementById('flash-link');
    flashLink.classList.remove('d-none');
    flashLink.style.opacity = '1';

    // Disparition après 3 secondes
    setTimeout(function() {
      flashLink.style.opacity = '0';
      flashLink.classList.add('d-none');
    }, 3000);
  }

  const button = document.querySelector('#copy-button')

  button.addEventListener(('click'), () => {
    showFlashLink()
  })
</script>

app/views/events/show.html.erb
<div class="body-container" data-controller="shuffle list-updater" >
  <h1 class="page-title">Voici la liste de cadeaux</h1>
  <div class="gift-list">
    <% @event.list.each_with_index do |gift, index| %>
      <% if index < 5 %>
        <div class="gift-item-row row-<%= index %>" data-shuffle-target="line"><div class="gift-item" data-shuffle-target="item" data-list-updater-target="listItem"><%= gift %></div><div class="shuffle" data-action="click->shuffle#update"><i class="fa-solid fa-refresh"></i></div></div>
      <% else %>
        <div class="gift-item-row  row-<%= index %> d-none" data-shuffle-target="line"><div class="gift-item" data-shuffle-target="item" data-list-updater-target="listItem"><%= gift %></div><div class="shuffle" data-action="click->shuffle#update"><i class="fa-solid fa-refresh"></i></div></div>
      <% end %>
    <% end %>
  </div>

  <div class="gift-list">
    <div class="body-category">
      <div class="category-title">Tu peux (encore) personaliser les résultats</div>
      <%= form_with(url: event_path, method: :patch) do |f| %>
        <%= f.text_field :post_prompt, as: :text %>
        <div class="custom-input" data-controller="new-prompt">
          <input type="text" id="new-prompt-box" class="new-input" placeholder="donne aux lutins plus de précisions" data-new-prompt-target="inputBox">
          <%= button_tag(type: 'submit', class: 'function-btn', id: 'addButton', data: { new_prompt_target: "addButton" } ,disabled: true) do %>
            <i class="fa-solid fa-paper-plane"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

<%= link_to 'Save my geeft list', updatelist_path(@event, list: @event.list), class: "big-btn", data: { env: Rails.env, id: @event.id, action: "click->list-updater#updateEvent" } %>

</div>

<script>
  // Sélectionnez les éléments input
  var sourceInput = document.getElementById('new-prompt-box');
  var targetInput = document.getElementById('post_prompt');

  // Vérifiez si les éléments existent avant de continuer
  if (sourceInput && targetInput) {
      // Ajoutez un écouteur d'événements pour détecter les changements de valeur dans le champ source
      sourceInput.addEventListener('input', function() {
          // Copiez la valeur du champ source dans le champ cible
          targetInput.value = sourceInput.value;
      });
  }
</script>

app/views/events/showdashboard.html.erb
<div class= "body-container" >

<% @events.order(:event_date).each do |event| %>
<%# <% console %>
<%#         ici je récupère bien event.id => 91 et event.user_id => 1        %>

    <div class="body-category">
      <div class="event name"><h1><%= event.event_name  %></h1></div>
        <div class="details">
          <div class="category-title">Pour: <%= event.lien %>, à l'occasion de <%= event.occasion %></div>
            <div class="category-title">Date: <%= event.event_date %></div>
              <div class="category-title">Description: <%= event.description %></div>
                <div class="category-title">Cagnotte: <%= event.cagnotte_url %></div>
        </div>
      <h1>Ma liste de geefts</h1>
      <% event.list.each do |gift| %>
        <ul>
          <li><%= gift %></li>
        </ul>
      <% end %>
    </div>


<% end %>

</div>

app/views/pages/savetodashboard.html.erb
<%# ici nous allons render nav bar, et organiser le dashboard avec les saved event
et autres features bonus  %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>